name: Bump version
on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    env:
      working-directory: src/unitypackage-test/Packages/com.apanloon.test-package

    steps:
      - uses: actions/checkout@v2

      - name: Trick npm to commit and tag
        working-directory: ${{ env.working-directory }}
        run: mkdir .git

      - name: Specify user
        run: |
          git config --global user.email "no-email@example.com"
          git config --global user.name "GitHub Action"

      - name: Bump version
        working-directory: ${{ env.working-directory }}
        run: npm version patch -m '[RELEASE] %s'

      - name: Check status
        working-directory: ${{ env.working-directory }}
        run: git status

      - name: Push
        working-directory: ${{ env.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
