name: Publish package
on:
  push:
    branches: [ main, test-action ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    env:
      working-directory: src/unitypackage-test/Packages/com.apanloon.test-package

    steps:
      - uses: actions/checkout@v2

      ## Bump version
      - name: Trick npm to commit and tag
        working-directory: ${{ env.working-directory }}
        run: mkdir .git

      - name: Specify user
        run: |
          git config --global user.email "no-email@example.com"
          git config --global user.name "GitHub Action"

      - name: Bump version
        working-directory: ${{ env.working-directory }}
        run: npm version patch -m '[RELEASE] %s'

      - name: Check status
        working-directory: ${{ env.working-directory }}
        run: git status

      - name: Push
        working-directory: ${{ env.working-directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push

      ## Publish

      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          # I don't know if this does anything - if I don't specify this in publish-config it appears to default to https://registry.npmjs.org/
          registry-url: 'https://npm.pkg.github.com'

      - run: npm install
        working-directory: ${{ env.working-directory }}

      - run: npm ci
        working-directory: ${{ env.working-directory }}

      - run: npm publish
        working-directory: ${{ env.working-directory }}
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
