# This is a basic workflow to help you get started with Actions

name: Publish package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build archive
        run: com.apanloon.test-package.zip qzip src/unitypackage-test/Packages/com.apanloon.test-package 
          
      - name: Publish archive
        run: |
          ls -l
          unzip -l com.apanloon.test-package.zip
          ls -l
          echo Completed!
