# This is a basic workflow to help you get started with Actions

name: Publish package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    env:
      working-directory: src/unitypackage-test/Packages/com.apanloon.test-package

    steps:
      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com@ApanLoon'
      - run: npm install
      - run: npm ci
        working-directory: ${{enc.working-directory}}
      - run: npm publish
        working-directory: ${{enc.working-directory}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
